# netlify.toml 配置文件

[[redirects]]
  from = "/assets/*"
  to = "https://readymag.website/u2578139204/5738442/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://readymag.website/u2578139204/5738442/:splat"
  status = 200
  force = true
  [redirects.headers]
    Content-Type = "text/html; charset=UTF-8"
